server:
  port: 8888

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: bt
  datasource:
    url: jdbc:mysql://localhost:3307/webnc_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

oauth2:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET}
  expiration:
    ms: 36000000