server:
  port: 8888

spring:
  application:
    name: bt
  datasource:
    url: jdbc:mysql://localhost:3307/webnc_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true